place1 = input("noun?")
place2 = input("adjective?")
place3 = input("noun?")
place4 = input("noun?")
place5 = input("verb ending in ing?")
place6 = input("noun?")
place7 = input("noun?")
place8 = input("plural noun?")
place9 = input("plural noun?")
place10 = input("plural noun?")

print("Harvard, Yale, %s, Stanford and other colleges around the world." % place1)
print("We've all heard of %s and, for some, have wanted to go to them. " % place2)
print("Going to %s has been considered necessary to be successful in life." % place3)
print("We go to %s to get a job, train for a career and pursue our dreams." % place4)
print("There's also the part of %s fun and maybe the chance of dating." % place5)
print("A lot of people consider %s the highlight of their life." % place7)
print("Other %s are not sure that college is worth it for a variety of reasons." % place8)
print("People should go to college because it helps you get %s, options, and %s." % (place9, place10))
