place1 = input("noun?")
place2 = input("adjective?")
place3 = input("noun?")
place4 = input("")
place5 = input("")
place6 = input("")
place7 = input("")
place8 = input("")
place9 = input("")
place10 = input("")

print("Harvard, Yale, %s, Stanford and other colleges around the world." % place1)
print("We've all heard of %d %d and, for some, have wanted to go to them. " % (place2, place3))
print("Going to %f has been considered necessary  to be successful in life." % place4)
print("")